### ISSUE TITLE
require_once APCal.php

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/apcal#16]
With 2.22 Beta 2 version, I get this error when I go to admin module (modules/APCal/admin/index.php):

`Warning: require_once(/modules/apcal/class/APCal.php): failed to open stream: No such file or directory in file /modules/APCal/admin/index.php line 25`

when I go to modules/APCal/admin/admission.php, I get this error:

`Warning: require_once(/modules/apcal/include/ro_contacthandler.php): failed to open stream: No such file or directory in file /modules/APCal/class/APCal.php line 26`

___
My config:
XOOPS Version	XOOPS 2.5.9-Beta2
PHP Version	7.0.15-0ubuntu0.16.10.4
mySQL Version	5.7.17-0ubuntu0.16.10.1

**Comment by cesagonchu** [comment]
I replaced all 

/modules/apcal/

with 

/modules/APCal/

and it resolved many bugs.

There were about a hundred.

I will make a pull request.

**Comment by mambax7** [comment]
No, we don't want that.  We want all directories in small letters. If something has to be adjusted, then please report bugs and it will be solved, but please don't change the directory to /APCal/

If you have an existing installation, you might change to /apcal/ in the database.

**Comment by cesagonchu** [comment]
Finally, no, changing the

/modules/apcal /

with

/modules/APCal/

Makes the module functional but I get 259 errors.

I prefer that the experts deal with it lol

**Comment by cesagonchu** [comment]
But don't close this issue, bugs are not fixed...

I tried to fix it with replacing names but that only make the module functional.


The bugs I found are real, and it was with your changes. That was before my proposal to change:

/modules/apcal/

with

/modules/APCal/

**Comment by mambax7** [comment]
Report the issues, and we'll try to fix them. 
But you also might consider extCal, as it probably will be the one that will be maintained

**Comment by mambax7** [comment]
Also, you might press Ctrl+F5, because it seems that sometimes you need to refresh the cache

**Comment by cesagonchu** [comment]
The issues are in the first message:

With 2.22 Beta 2 version, I get this error when I go to admin module (modules/APCal/admin/index.php):

`Warning: require_once(/modules/apcal/class/APCal.php): failed to open stream: No such file or directory in file /modules/APCal/admin/index.php line 25`

when I go to modules/APCal/admin/admission.php, I get this error:

`Warning: require_once(/modules/apcal/include/ro_contacthandler.php): failed to open stream: No such file or directory in file /modules/APCal/class/APCal.php line 26`

Dedale told me that he will maintain his module once we have resolved all the bugs with Xoops 2.5.9.
A  programmer will help him to make additions to the module after that. For now they are too busy to help.

I will make another tests with another browser and reinstalling but I don't think I have cache problems.
I often use CCleaner.

Of course I will test extCal too. I test all modules.
___
My config:
XOOPS Version	XOOPS 2.5.9-Beta2
PHP Version	7.0.15-0ubuntu0.16.10.4
mySQL Version	5.7.17-0ubuntu0.16.10.1

**Comment by mambax7** [comment]
It seems like you didn't update the module properly :( 

The line 25 in the repository is different:
https://github.com/XoopsModules25x/apcal/blob/master/admin/index.php

**Comment by cesagonchu** [comment]
Ok, I will do another tests.

So now, you recommand me not to rename the module?

apcal-master -> apcal

and not

apcal-master -> APCal

Is that right?

**Comment by mambax7** [comment]
Yes, that's correct

**Comment by cesagonchu** [comment]
Okay, sorry, you were right. These bugs are no longer there. We can close this issue.
