### ISSUE TITLE
_AM_APCAL_COPYRIGHT not defined

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/apcal#19]
When I display an event (modules/apcal/?event_id=0000000001&action=View&caldate=2017-3-18), I can see that a define has no name (_AM_APCAL_COPYRIGHT):

![image](https://cloud.githubusercontent.com/assets/4613970/24069791/0a71a17e-0bb1-11e7-99ef-0a72088b73e2.png)

**Comment by mambax7** [comment]
This should be fixed

**Comment by cesagonchu** [comment]
Can you send your correction:
https://github.com/mambax7/apcal/commit/ed98254385e01f12f8c8b29a5c90de8e34035d8c

to the master branch?
https://github.com/XoopsModules25x/apcal/

It works with your correction.

Thanks!

**Comment by mambax7** [comment]
Done
