### ISSUE TITLE
undefined constant _MD_APCALAM_APCALPERMADDOK

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/apcal#25]
Tried your version:
https://github.com/mambax7/apcal/tree/c6f45a269bfc5a5a8f2b1a85eeff6a568f493e42

When I set permissions, I get this error:
undefined constant _MD_APCALAM_APCALPERMADDOK in file /modules/apcal/admin/mygroupperm.php line 97
![image](https://cloud.githubusercontent.com/assets/4613970/24327824/456b77ca-11db-11e7-8bac-6449301ed16b.png)

**Comment by mambax7** [comment]
See: https://github.com/XoopsModules25x/apcal/pull/27 and https://github.com/XoopsModules25x/apcal/pull/28
