### ISSUE TITLE
uploads/APCal can not delete it

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/apcal#8]
It was necessary that I logged in as root to be able to delete the APCal folder in /uploads, on the ftp.

Can you change it?

**Comment by mambax7** [comment]
Is your /uploads folder set with 777 ?

**Comment by cesagonchu** [comment]
Yes, but /apcal is set with 755 and owner 33 and group 33 whereas as a user I am owner 1000 and group 33.
This folder apcal inside /uploads is created by the module.

**Comment by geekwright** [comment]
Can you normally delete entries in the xoops_data/cahces/smarty_compile directory?

Is sounds like you've added yourself to the www-data group, which is good, but the umask for the webserver process is probably 0022. This means that by default, only the owner gets full permissions, so new files are set 0644 and folders and folders are 0755 -- read only for group, and would have www-data as both the user and group.

Research this for yourself first to make sure it will work for you, but you should be able to add a line to the end of /etc/apache2/envvars like this:
```
umask 0002
```
Then do an `sudo service apache2 restart`. After that, any new files should be 0664 and new folders 0775, so as a member of the www-data group, you should have control.

There are a lot of different ways to configure a server. It sounds like you are using the default ubuntu apache2 mod_php, so this should work for you.

PS, the uploads folder should be set `chmod 0775` and `chgrp www-data`. Only the user and group should need write permission.

**Comment by cesagonchu** [comment]
Thx Richard. Yes I can delete it.
I will do your manipulation tomorrow because it is not me who manages the dedicated server.

**Comment by cesagonchu** [comment]
Ok, problem fixed, thx! :-)
