### ISSUE TITLE
Errors when I want to display a block

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/apcal#9]
When I want to display a block, I get these errors:

Notice: Undefined offset: 2 in file /include/cp_header.php line 32

Error: Call to a member function getVar() on boolean in file /include/cp_header.php line 34

___
My config:
XOOPS Version	XOOPS 2.5.9-Beta2
PHP Version	7.0.15-0ubuntu0.16.10.4
mySQL Version	5.7.17-0ubuntu0.16.10.1

**Comment by zyspec** [comment]
Does this happen with all the blocks or just some? I assume what you're doing is enabling a block and you get this error when you try and go to the page that loads the block, correct?  Can you tell me which block you're trying to load so I can look at it (them) specifically?

**Comment by cesagonchu** [comment]
Thx, finally it's only happen with MiniCalendar block.
`<img class="tooltip" id="img49" onclick="system_setStatus( { fct: 'blocksadmin', op: 'display', bid: 49, visible: 1 }, 'img49', 'admin.php' )" src="/modules/system/images/icons/transition/cancel.png" alt="Display block MiniCalendar" title="Display block MiniCalendar">`

The other blocks shows but even with permissions, I get this message:

> Sorry, you don't have the permission to access this area.

even if I have set permissions.
